name: Docker build and push images

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Image name'
        required: true
        type: string
      project-path:
        description: 'Project path'
        required: true
        type: string

jobs:
  build:
    name: Build images

    permissions:
      id-token: write
      packages: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: ${{ inputs.project-path }}
        file: ${{ inputs.project-path }}/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:latest
    